baseURL = 'https://www.okrust.com/'
languageCode = 'zh-CN'
title = 'okrust'
theme = 'diary'
hasCJKLanguage = true
paginate =  10
paginatePath = "page"

# 启用 Emoji; see emoji-cheat-sheet.com
enableEmoji = false

# 创建robots.txt，建议设置为true
enableRobotsTXT = false

copyright = "okrust所有"

# goole数据统计
googleAnalytics = "G-GT370SNKC1"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1

[params]
favicon = "favicon.png"

[frontmatter]
  lastmod = [":fileModTime", "lastmod"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github-dark"
    tabWidth = 4