name: github pages

on:
  push:
    branches:
      - main  # 这里是提交到master分支就立即触发job
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.2' 
          extended: true 

      - name: Build
        run: hugo --minify

      - name: Deploy Github
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 这里不用动, 默认就好
          publish_dir: ./public  # 注意是hugo的public文件夹
          cname: www.okrust.com # cname
          
      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Configure SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          echo "${{ secrets.SERVER_IP }} ssh-rsa ${{ secrets.SSH_PUBLIC_KEY }}" >> ~/.ssh/known_hosts

      - name: Deploy to Cloud Server
        run: rsync -avz -e "ssh -i private_key" --delete public/ root@${{ secrets.SERVER_IP }}:/var/www/hugo
